openapi: 3.0.3
info:
  title: Todo API Specification
  version: '242'
  description: API documentation for the Todo bounded context.
servers:
  - url: /api/v1
    description: Development Server
tags:
  - name: Todo
    description: Operations related to the Todo bounded context.
paths:
  /create-todo-item:
    post:
      summary: Create Todo Item
      description: Executes the "Create Todo Item" command. ...
      operationId: createTodoItem
      tags:
        - Todo
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoItemRequest'
  /update-todo-item:
    post:
      summary: Update Todo Item
      description: Executes the "Update Todo Item" command. ...
      operationId: updateTodoItem
      tags:
        - Todo
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoItemRequest'
  /complete-todo-item:
    post:
      summary: Complete Todo Item
      description: Executes the "Complete Todo Item" command. ...
      operationId: completeTodoItem
      tags:
        - Todo
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteTodoItemRequest'
  /delete-todo-item:
    post:
      summary: Delete Todo Item
      description: Executes the "Delete Todo Item" command. ...
      operationId: deleteTodoItem
      tags:
        - Todo
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTodoItemRequest'
  /fetch-todo-list:
    get:
      summary: Fetch Todo List
      description: Retrieves data based on the "Fetch Todo List" query. This is a synchronous query operation.
      operationId: fetchTodoList
      tags:
        - Todo
      responses:
        '200':
          description: Successful retrieval of data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
  /get-todo-item-details/{todoID}:
    get:
      summary: Get Todo Item Details
      description: Retrieves data based on the "Get Todo Item Details" query. This is a synchronous query operation.
      operationId: getTodoItemDetails
      tags:
        - Todo
      responses:
        '200':
          description: Successful retrieval of data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '400':
          $ref: '#/components/responses/BadRequest'
      parameters:
        - name: todoID
          in: path
          required: true
          schema:
            type: string
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: An error occurred.
    TodoItem:
      type: object
      description: Represents a Todo Item in the system.
      properties:
        todoID:
          type: string
          description: The Todo ID of the Todo Item.
          example: '1'
        todoTitle:
          type: string
          description: The Todo Title of the Todo Item.
          example: Buy groceries
        description:
          type: string
          description: The Description of the Todo Item.
          example: Weekly shopping
        dueDate:
          type: string
          description: The Due Date of the Todo Item.
          example: '2023-10-15'
        priorityLevel:
          type: string
          description: The Priority Level of the Todo Item.
          example: High
        category:
          type: string
          description: The Category of the Todo Item.
          example: Personal
        tags:
          type: string
          description: The Tags of the Todo Item.
          example: Shopping
        completionDate:
          type: string
          description: The Completion Date of the Todo Item.
          example: '2023-10-16'
        completionNotes:
          type: string
          description: The Completion Notes of the Todo Item.
          example: Done
        deletionReason:
          type: string
          description: The Deletion Reason of the Todo Item.
          example: Not needed
      required:
        - todoID
        - todoTitle
    CreateTodoItemRequest:
      type: object
      properties:
        todoTitle:
          type: string
          example: Buy groceries
        description:
          type: string
          example: Weekly shopping
        dueDate:
          type: string
          example: '2023-10-15'
        priorityLevel:
          type: string
          example: High
        category:
          type: string
          example: Personal
        tags:
          type: string
          example: Shopping
      required:
        - todoTitle
    UpdateTodoItemRequest:
      type: object
      properties:
        todoID:
          type: string
          example: '1'
        todoTitle:
          type: string
          example: Buy groceries
        description:
          type: string
          example: Weekly shopping
        dueDate:
          type: string
          example: '2023-10-15'
        priorityLevel:
          type: string
          example: High
        category:
          type: string
          example: Personal
        tags:
          type: string
          example: Shopping
      required:
        - todoID
        - todoTitle
    CompleteTodoItemRequest:
      type: object
      properties:
        todoID:
          type: string
          example: '1'
        completionDate:
          type: string
          example: '2023-10-16'
        completionNotes:
          type: string
          example: Done
      required:
        - todoID
    DeleteTodoItemRequest:
      type: object
      properties:
        todoID:
          type: string
          example: '1'
        deletionReason:
          type: string
          example: Not needed
      required:
        - todoID
  parameters:
    TodoItemId:
      name: todoID
      in: path
      required: true
      description: The unique identifier for the Todo Item.
      schema:
        type: string
  responses:
    BadRequest:
      description: 'Bad Request: The server cannot or will not process the request due to something that is perceived to be a client error.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 'Not Found: The server can not find the requested resource.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: 'Internal Server Error: The server has encountered a situation it doesn''t know how to handle.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
